# -*- coding: utf-8 -*-
# Generated by Django 1.9.2.dev20160114123008 on 2016-01-15 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20140909_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={},
        ),
    ]
