# -*- coding: utf-8 -*-
# Generated by Django 1.9.2.dev20160114123008 on 2016-01-15 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_fk-protections'),
        ('schedule', '0003_remove_implicit_ordering'),
    ]

    operations = [
    ]
