# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_schedule_item_update_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='video',
            field=models.BooleanField(
                default=False, help_text='Venue has video coverage'),
        ),
    ]
