# Generated by Django 5.0.9 on 2024-10-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_longer_email_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketTypeTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name="tickettype",
            name="tags",
            field=models.ManyToManyField(to="tickets.tickettypetag"),
        ),
    ]
