# Generated by Django 4.1.1 on 2023-10-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20160329_2003"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="github_username",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="twitter_handle",
        ),
    ]
