# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_author_helptext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talktype',
            options={'ordering': ['id']},
        ),
    ]
