# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0012_add_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='talk_type',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='talks.TalkType'),
        ),
    ]
