# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0013_talk_types_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='video',
            field=models.BooleanField(default=True, help_text='By checking this, you are giving permission for the talk to be videoed, and distributed by the conference, under a license of their choice.'),
        ),
        migrations.AddField(
            model_name='talk',
            name='video_reviewer',
            field=models.EmailField(blank=True, help_text="Email address of a person who will be allowed to review and approve your video details. Ideally, a second set of eyes who is not a busy conference presenter. But you can specify yourself, if you can't think of anyone else who would care.", max_length=254, null=True),
        ),
    ]
