# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0014_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='status',
            field=models.CharField(choices=[(b'A', b'Accepted'), (b'R', b'Not Accepted'), (b'C', b'Talk Cancelled'), (b'U', b'Under Consideration'), (b'S', b'Submitted'), (b'P', b'Provisionally Accepted'), (b'W', b'Talk Withdrawn')], default=b'S', max_length=1),
        ),
    ]
