# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-06 16:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markitup.fields
import wafer.talks.models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0016_add_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
