# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0017_talk_submission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='talktype',
            name='accept_late_submissions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talktype',
            name='submission_deadline',
            field=models.DateTimeField(default=None, null=True, blank=True),
        ),
    ]
