# Generated by Django 2.2.15 on 2020-08-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0018_talk_type_submission_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkurl',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
