# Generated by Django 2.2.15 on 2020-08-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0019_talkurl_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkurl',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
