# Generated by Django 3.0.3 on 2020-10-11 12:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markitup.fields
import wafer.talks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talks', '0020_talk_url_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='talktype',
            name='show_speakers',
            field=models.BooleanField(default=True, help_text='Whether to show the authors for this talk type in the speakers list', verbose_name='Show authors in speakers list'),
        ),
    ]
