# Generated by Django 4.2.6 on 2023-10-08 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("talks", "0022_talk_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="talktype",
            name="show_pending_submissions",
            field=models.BooleanField(
                default=False,
                help_text="Whether to publicly show pending submissions, before acceptance",
                verbose_name="show pending submissions",
            ),
        ),
    ]
