# Generated by Django 4.2.9 on 2025-07-09 15:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markitup.fields
import wafer.talks.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("talks", "0023_talktype_show_pending_submissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "permissions": (
                    ("view_all_reviews", "Can see all reiews via the api"),
                ),
            },
        ),
    ]
