# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0006_allow_blank_files_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='files',
        ),
        migrations.AddField(
            model_name='taggedfile',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='sponsors.Sponsor'),
        ),
        migrations.AddField(
            model_name='taggedfile',
            name='tagged_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.File'),
        ),
    ]
