# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_allow_blank_files_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cache_time',
            field=models.IntegerField(default=-1, help_text='Length of time (in seconds) to cache the page for dynamic page content. A negative value means this page is not dynamic and it will be not be regenerated until it is next edited.'),
        ),
    ]
