# Generated by Django 5.0.3 on 2025-10-11 09:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_menu_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="schedule_duplicates",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
